Improve docs for tier prices
customgento/docs pull request #21
Opened 2021-11-17 13:38 UTC by norgeindian

2021-11-17 13:43 UTC, sprankhub requested changes

2021-11-17 13:43 UTC, sprankhub commented on pages/tier-prices-for-configurable-products-m2.md
> +- magento/module-config: ~101.1|~101.2
```suggestion
- magento/module-config: ~101.1||~101.2
```

2021-11-17 13:43 UTC, sprankhub commented on pages/tier-prices-for-configurable-products-m2.md
> +To be able to use the features of this module, you need a configurable product with several child products. For each child product, you can now define (different) tier prices for specific quantities.
The text is okay, but it has nothing to do with the configuration. IMHO, it should go into the "Description" section. It could replace / complement the first sentence.

2021-11-18 09:40 UTC, norgeindian commented on pages/tier-prices-for-configurable-products-m2.md
> +To be able to use the features of this module, you need a configurable product with several child products. For each child product, you can now define (different) tier prices for specific quantities.
You're right. Changed it

2021-11-18 09:48 UTC, sprankhub approved these changes

2021-11-18 09:48 UTC, sprankhub commented on pages/tier-prices-for-configurable-products-m2.md
> +- magento/module-config: ~101.1||~101.2
```suggestion
- magento/module-config: `~101.1||~101.2`
```

2021-11-18 10:00 UTC, merged