Dev 241 child product data
customgento/docs pull request #48
Opened 2023-11-27 09:56 UTC by norgeindian

2023-11-27 15:15 UTC, Irinina requested changes

2023-11-28 09:12 UTC, norgeindian commented on pages/child-product-data-module.md
> +title: Child Product Data module
No, I'm with you. We all know, that it is a module. Will try to get rid of it.

2023-11-28 09:20 UTC, norgeindian commented on pages/child-product-data-module.md
> +summary: "The Child Product Data Viewer Module is a powerful extension for Magento, designed to enhance the user experience and provide customers with detailed information about products. With this m
Better like this?

2023-11-28 09:25 UTC, norgeindian commented on pages/child-product-data-module.md
> +3. **Universal Theme Support:** This module has been carefully crafted to be compatible with a wide range of themes. Whether you're using the default Magento theme or any other custom theme, the Chil
Yeah, I think as soon as you enter the proper identifiers it should work in any case.

2023-11-28 09:28 UTC, norgeindian commented on pages/child-product-data-module.md
> +This module is built by default for a clean Hyva Theme.
Let's get rid of "Viewer". I think this way is okay, what do you think?

2023-11-28 09:30 UTC, norgeindian commented on pages/child-product-data-module.md
> +After entering the correct identifiers, please save the configuration and clear the cache. From now on, the module will work as expected and show for example the adapted product name and the SKU as s
For a standard hyva theme, that will not work. We will update the values anyway.

2023-11-28 09:30 UTC, norgeindian commented on pages/child-product-data-module.md
> +![Output]({{ "images/child-product-data/child-product-data-output.png" }} "Output")
Yeah, I'm with you

2023-11-28 09:31 UTC, norgeindian commented on pages/child-product-data-module.md
> +- hyva-themes/magento2-theme-module: `~1.1`
Good point, had that in the review as well. Will remove it and hope, that the code changes the same way as well.

2023-11-28 19:50 UTC, Irinina requested changes

2023-11-28 19:50 UTC, Irinina commented on pages/child-product-data-m2.md
> +1. **Dynamic Change of Product Data:** As soon as a customer chooses an option of a configurable product, the values of the following attributes are adapted::
```suggestion
1. **Dynamic Change of Product Data:** As soon as a customer chooses an option of a configurable product, the values of the following attributes are adapted:
```

2023-11-28 19:50 UTC, Irinina commented on pages/child-product-data-module.md
> +After entering the correct identifiers, please save the configuration and clear the cache. From now on, the module will work as expected and show for example the adapted product name and the SKU as s
Ah okay, and what happens, if we use a Hyvä child theme or Luma and don't fill in some identifiers, because we don't want to update e.g. the sliders or the short description?
For me, it's somehow not clear from the documentation, that we need to fill in everything and can't update only a subset of the data.

2023-11-29 10:32 UTC, norgeindian commented on pages/child-product-data-module.md
> +After entering the correct identifiers, please save the configuration and clear the cache. From now on, the module will work as expected and show for example the adapted product name and the SKU as s
Then it will surely not really work, indeed. I just don't know how to properly write that.
Maybe we simply skip, that it will work anyway with Hyvä and just write, that you can leave them empty to not update the specific attribute ?

2023-11-29 10:55 UTC, Irinina approved these changes

2023-12-20 13:23 UTC, merged